spring:
  application:
    name: cangxi
  datasource:
    url: jdbc:mysql://:3306/cangxi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
springfox:
  documentation:
    swagger-ui:
      enabled: true